apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cook-app-two
  namespace: jeremy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: cook-app-two
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: tolerations
      value: test
    - name: affinity
      value: ["0.0.103","0.0.104"]
  serviceClaims:
    - name: spring-properties
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: cook-app-two-config-claim
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  env:
    - name: SPRING_CONFIG_IMPORT
      value: "optional:configtree:${SERVICE_BINDING_ROOT}/spring-properties/"
    - name: SPRING_CLOUD_CONFIG_ENABLED
      value: "false"
    - name: SPRING_PROFILES_ACTIVE
      value: "prod"
  source:
    git:
      url: ssh://git@github.com/x95castle1/cook-app-two
      ref:
        branch: main