apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sso-example-app-tap
  description: My incredible App SSO Sample App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=sso-example-app-tap'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
