logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE


org:
  springframework:
    cloud:
      bindings:
        boot:
          oauth2:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: env,info,health

spring:
  security:
    oauth2:
      client:
        provider:
          appsso:
            issuer-uri: https://dev-pbi3csp88xs4ezg5.us.auth0.com/
        registration:
          sso-example-app-tap-client-registration:
            provider: appsso
            client-id: xxxx
            client-secret: xxxxx
            scope: openid, email, profile

